### ISSUE TITLE
L2J_EventEngine Block ALL Custom NPC

### ISSUE THREAD

**Issue by AntoineKouma** [AthenaEventEngine/AthenaCore#106]
Hello everyone, i just notice after EventEngine install all other custom npc (gm shop, buffer, gatekeeper) stop work and i can only target them. Anyone know what is about? Maybe is l2java.jar error? I use the last revision of l2jserver.com!
Also if you can give me the last core patch for my revision cause all other dont work and i get message olympiad and other dosent exist!

Btw thanks in advance!

**Comment by Lucheti29** [comment]
https://github.com/u3games/L2J_EventEngine/pull/107

**Comment by Lucheti29** [comment]
Fixed.
