### ISSUE TITLE
Friendly fire bugged

### ISSUE THREAD

**Issue by Lucheti29** [AthenaEventEngine/AthenaCore#109]
[ENG] You can attack members of your team
[ESP] Podés atacar a miembros de tu equipo

**Comment by u3games** [comment]
https://github.com/u3games/L2J_EventEngine/pull/117 ;)

**Comment by u3games** [comment]
Fix https://github.com/u3games/L2J_EventEngine/commit/51970d966c2f8fac09c0c6442818829855c8f842
