### ISSUE TITLE
Modificación del título

### ISSUE THREAD

**Issue by Lucheti29** [AthenaEventEngine/AthenaCore#11]
Al ingresar a un evento, si deslogueás en medio de un evento, no te restaura el título original que tenías al volver a loguear.

**Comment by Lucheti29** [comment]
Quizás sólo pasa cuando cerrás el proceso servidor por la fuerza. Hay que testear.

**Comment by fissban** [comment]
si cerras el servidor indevidamente no permitis q vuelva a modificar el titulo de los personajes......pero se puede mejorar si e lugar de cambiar los titulos ajustamos el paquete como "userInfo"

**Comment by Lucheti29** [comment]
Me parece una mejor opción (Y)

**Comment by u3games** [comment]
Bug Fix - https://github.com/u3games/L2J_EventEngine/commit/6c4e507cfeb8cab158ce81f66c201499b703a623
