### ISSUE TITLE
Not Found code in Java 6 :(

### ISSUE THREAD

**Issue by l2draco** [AthenaEventEngine/AthenaCore#113]
Hola, podria adaptar el codigo para java 6 ?

**Comment by Lucheti29** [comment]
No. Me parece que es un despropósito usar Java 6 cuando existe Java 8 y estamos en vísperas de Java 9. Por otra parte, el proyecto utiliza estructuras que son exclusivamente de Java 8 y nos ayudan a mantener, en general, la concurrencia.

Por otra parte, queremos armar un software moderno, y usar Java 6 va en contra de ese principio.

Lo siento :cry:

**Comment by l2draco** [comment]
El project que uso es java 6 :s , no tienes uno tutorial de como actualizar el projecto para java 7 our 8 enton ?

**Comment by Lucheti29** [comment]
No, no tengo tutorial. Más allá de eso, no debería haber problemas de cambiar de Java 6 a 7 u 8. Fijate de cambiar las variables de entorno y en el classpath de Eclipse (si es que usás Eclipse) para que use la versión de Java correspondiente. Por otra parte, descargá el JDK correspondiente.

Igual, buscando un poco no creo que tengas problemas en encontrar algo. Por ejemplo, este post (aunque no tiene una solución pero más o menos dice qué hay que hacer) http://stackoverflow.com/questions/21215338/upgrade-a-java-6-project-to-java-7-in-eclipse

Google y Stackoverflow son tus amigos.
