### ISSUE TITLE
Event All vs All - Bug Range Spawn

### ISSUE THREAD

**Issue by u3games** [AthenaEventEngine/AthenaCore#114]
Por defecto el rango es muy bajo y todos aparecen al lado uno del otro. Lo ideal sería o añadir efectos de spawn (lo que comentamos de invislbe y efectos visuales) o aumentar el rango de spawn y que sea aleatorio.

Actualmente le he aumentado el rango actual a 500 y he encontrado bugs. Al spawnear por 5 vez por ejemplo, el rango se sale del área del evento. Es como si tomase el ultimo punto de respawn y desde ese punto hace el rango de 500, en vez del origen inicial de las coordenadas.

Yo lo he probado en coliseum, y al comienzo todo bien pero cuando mueres ya varias veces, el spawn se mueve mucho de su punto inicial y apareces en las gradas y cuantos más spawns más lejos...

**Comment by l2draco** [comment]
Poderia hacer como el Event Death Match, ustedes en vez de colocar rango por spawn, colocar varios spawn com locs, para los pjs nasceren aleatoriamente nestas locs...
Desculpa por mal español.

**Comment by Lucheti29** [comment]
@l2draco You can write in english. And yes, we have in mind add multiple locations :smile:

**Comment by l2draco** [comment]
Sorry, I am that I am pt-br, only speak en español and little.
I just wanted to give this tip since the bug is because of the random respawns.
;)

**Comment by Lucheti29** [comment]
Spanish or english is ok. We'll check this soon.

**Comment by ghost** [comment]
Can be checked with lastest versions?

**Comment by Lucheti29** [comment]
It needs a rework.

**Comment by Lucheti29** [comment]
Fixed. Now you can use several locations as spawn points, so you don't need a random to determinate the location. Checkout https://github.com/AthenaEventEngine/AllVsAll/blob/master/src/main/resources/config.conf
