### ISSUE TITLE
NPE en Settings

### ISSUE THREAD

**Issue by Lucheti29** [AthenaEventEngine/AthenaCore#12]
![npe](https://cloud.githubusercontent.com/assets/4108820/8469037/b53eb5fa-204a-11e5-9806-0b44b4892ce5.JPG)

**Comment by u3games** [comment]
Already fix in new version. thx for report ^^

**Comment by Lucheti29** [comment]
Remember add the link to pr https://github.com/u3games/L2J_EventEngine/pull/8
