### ISSUE TITLE
Votos

### ISSUE THREAD

**Issue by Lucheti29** [AthenaEventEngine/AthenaCore#13]
-No hay forma de retirar el voto
-El voto no se va al desloguear
-No es intuitiva la interfaz para votar

**Comment by luksdlt92** [comment]
Solucionado el punto 3: ahora es más intuitiva la interfaz

**Comment by Lucheti29** [comment]
Punto 2 solucionado -> https://github.com/u3games/L2J_EventEngine/pull/22

**Comment by Lucheti29** [comment]
Falta agregar algo para borrar el voto que no sea desloguear.

**Comment by fissban** [comment]
El logo de las olimpiada en el html es demasiado grande y ocupa mucho espacio, yo lo borraria y agregaria una leyenda explicando brevemente como funciona....primero los votos, luego registrarse...etc etc etc

**Comment by Lucheti29** [comment]
Creo que la interfaz gráfica actual se entiende bastante, además que aparece una leyenda de qué hay que hacerse. Por otro lado, el logo de las olimpiadas me gusta como queda, le da cierto tono elegante.

Para mí, cuando ya se votó debería habilitarse un botón para cancelarlo y listo.

**Comment by u3games** [comment]
El mismo boton para votar por el evento, cuando pulsas de nuevo sobre el pues que se elimine el voto directamente. Sobre el html, la imagen de olimpiadas.. ya esta actualizado ;)

**Comment by u3games** [comment]
Punto 1 --> https://github.com/u3games/L2J_EventEngine/pull/56

**Comment by u3games** [comment]
Si añadimos que sea el mismo botón, tendriamos que poner una restrigción.. es decir, cuando por ejemplo quede 1 minuto para finalizar el tiempo de votación, no puedas cambiar tu voto.

Asi evitariamos votos troll xD

**Comment by fissban** [comment]
Excepto lo del voto al deslogear el resto ya esta todo, si @luksdlt92 le parece podemos cerrar esto

**Comment by Lucheti29** [comment]
1) El voto ya se va al desloguear, así que existe una forma y está bien que no puedan sacarlo con una opción porque podría generar problemas (tampoco es la muerte de nadie).
2) Lo que dije arriba.
3) Después de bastante tiempo probando, me parece que la interfaz está ok.

Cierro :dancers:
