### ISSUE TITLE
Capture the Flag. Equal chances.

### ISSUE THREAD

**Issue by gajet5** [AthenaEventEngine/AthenaCore#131]
One flag is closer.
The chances are not equal.

https://i.gyazo.com/f5d88d0047e64c6491a4e9dc8c468171.png
https://i.gyazo.com/a3bb4bdb332493262faff9cefe929d8c.png

My suggestion.

```
_flagSpawn.put(getSpawnManager().addEventNpc(FLAG, x, y, z, 0, Team.NONE, th.getTeamType().name(), false, instanceId), tt);

_holderSpawn.put(getSpawnManager().addEventNpc(HOLDER, x, y - 100, z, 0, Team.NONE, th.getTeamType().name(), false, instanceId), tt);

```

Set a flag or the holder of the left or right.

**Comment by ghost** [comment]
Please can be checked with lastest version?

**Comment by Lucheti29** [comment]
Still happens

**Comment by Lucheti29** [comment]
Fixed. Checkout https://github.com/AthenaEventEngine/CaptureTheFlag
