### ISSUE TITLE
Order and concert in project

### ISSUE THREAD

**Issue by ghost** [AthenaEventEngine/AthenaCore#137]
Anybody can commit this patch please?
https://gist.github.com/Sacrifice78/dcc456b75915f8515192e9600b560eb7

**Comment by ghost** [comment]
@Zephyr ¿Se podria cambiar lo de net/sf... por github/u3games? ¿no?

**Comment by Sacrifice78** [comment]
O ... eventengine/u3games

**Comment by ghost** [comment]
src/main/java/net/sf/eventengine
src/main/java/com/u3games/eventengine

**Comment by Lucheti29** [comment]
@Sacrifice78 Se puede. Lo que no entiendo es el dist, ¿qué se supone que hace?

**Comment by Lucheti29** [comment]
Refactor done.

**Comment by ghost** [comment]
Lo que hice fue traducir al ingles algunos textos que estaban en "español" y quitarles los espacios en blanco del final de las clases. Al igual que convertir todas las clases y ficheros a formato windows (habian bastantes en formato unix), ya sabes los LF a CR LF.

**Comment by Lucheti29** [comment]
Eso puede explicar muchas cosas... querés hacer esos cambios en pull request separados? Es decir, lo que está en español a inglés en uno, lo del formato en otro, etc. Sino quedan muchos cambios en un diff gigante y es difícil leer por si se introduce algún bug. Se entiende?

**Comment by u3games** [comment]
@Sacrifice78 antes que nada. muchas gracias por la colaboración. Como dijo @luksdlt92, estamos intentando hacer el proyecto lo más organizado posible, por ello pedimos que cada cambio sea puesto en un solo pr, así tenemos todo más controlado y organizado. Sobre reducir el net/sf... por github/u3games seguramente lo haremos más adelante ^^

Un saludo.

**Comment by Lucheti29** [comment]
@u3games ya está hecho eso

**Comment by ghost** [comment]
Me consta!

**Comment by ghost** [comment]
Es un placer @u3games 👍

**Comment by ghost** [comment]
Cierro esta issue, volveré...
