### ISSUE TITLE
EventEngineManager

### ISSUE THREAD

**Issue by Lucheti29** [AthenaEventEngine/AthenaCore#15]
Tiene una mezcla importante entre el uso de variables estáticas y el patrón singleton. Es una cosa o la otra.

**Comment by fissban** [comment]
la mezcla no es gran cosa, el singleton solo lo declaro para q se cree una unica instancia  de exactamente lo q yo quiero y evitar q por error se vuelva a cargar algo....como por ejemplo la lectura de xml...la carga del archivo debe ser unica pero los metodos q se encargan de leer los datos no requieren q sean de esa instancia o q se genere una para acceder a sus datos....claro esta q no soy un experto en el area y puedo tener conceptos erroneos

**Comment by Lucheti29** [comment]
No soy super-pro en patrones de diseño, pero generalmente se suele usar una cosa o la otra. Más que nada este issue lo puse para recordar chequear el tema.

Principalmente, se están declarando métodos y variables estáticas con una expresión que corresponde a variable de instancia (variable estática -> todo mayúscula // variable de instancia -> _todo minúscula).

Por otra parte, si bien no lo vi bien bien, creo que se hace un getInstance del EventEngineManager y casi nunca se lo pide.

Después lo veo bien.

**Comment by fissban** [comment]
Este tema ya esta revisado y solucionado
