### ISSUE TITLE
L2 event engine

### ISSUE THREAD

**Issue by Nayden87** [AthenaEventEngine/AthenaCore#160]
Hello guys, im so sorry if im boring you but i tried to solve this problem alone for hours before to ask your help.

I build a l2jserver a few weeks ago and i had to do it with normal svn as github is not working. So my revisions are.

Datapack: 10490
Server: 6670

Basically i tried to instal event engine.

https://github.com/AthenaEventEngine/AthenaCore/wiki

But my problem is that i dont have grindle installed (i have it on eclipse but not in the server project folder) but i dont have a file .bat to load the jar and make it recognized from eclipse.

I tried to build the jar in eclipse using the build Path in library but nothing. i have an icon with eventengine name and a question mark on it. And right now i dont know what can i do to make it work properly.

Thank you so much for you help guys and sorry again.

**Comment by Lucheti29** [comment]
Hi. I'm glad to help you.

You just need to put the release jar into the libs folder and compile the l2jserver as always. This step is because the compiler creates the class to for each dependency inside the libs folder.

Then, change the l2jserver.jar from game folder and add the engine jar into the libs folder.

The last step is add the starter script (like the wiki says).

Anyway, i'm not sure if the engine works on your server versión, maybe it's too old.

Tell us if it worked.

Regards.

**Comment by Nayden87** [comment]
So I did it and doesn't work at all.

So just confirm me a think my friend please.
When I put the jar inside the libs folder I need to open the ant view (eclipse) and compile the build.xml from the server and that is yeah?

Because I did it and I could spawn the npc but I can't talk to him. If I click on it nothing happens. 
And can you suggest me the new release svn for h5?

**Comment by Lucheti29** [comment]
Did you add the starter script? Did you ser any error in console?

**Comment by Nayden87** [comment]
First of first HAppy new year guys and thank you for your job.

And are you talking about with script?

The first time when i started the console i had a very big error talking about the listener but to be honest i dont remember the code.

**Comment by Lucheti29** [comment]
Happy new year!

I'm talking about the EventEngineStarter.java 

Can you add a screen about the error?

**Comment by Nayden87** [comment]
![errore](https://cloud.githubusercontent.com/assets/19366377/21581691/c24598b8-d034-11e6-9f28-b9b9a9148cad.jpg)

I put everything as said in the guide. And this is the error

**Comment by Lucheti29** [comment]
The good news is the engine was loaded. The bad news is the versión of l2j is too old. :(

**Comment by Nayden87** [comment]
Yeah I saw that the even has been loaded. There is any chance to fix it? Or can you suggest me a new release of l2j high five to try? Because since when they blocked the git hub I had problem to find an svn trunk for h5

**Comment by Nayden87** [comment]
Sorry for the spam. in the log error of l2eventengine i have this:

Error on: C:\Users\elaou\Desktop\High Five\game\data\scripts\custom\events\EventEngine\EventEngineStarter.java.error.log
Line: -1 - Column: -1

java.lang.reflect.InvocationTargetException

**Comment by Lucheti29** [comment]
It's for the error in console.

You can download l2j from bitbucket repository https://bitbucket.org/l2jserver/

If you are interested, there is a new fork that contains a lot of fixes (i'm part of that Team too). The URL is u3g-l2jdev.united-extreme.com

**Comment by Nayden87** [comment]
and can i use eclipse? there is anyguide how to link t to eclipse or any other IDE so i canf ix stuffs?
Sorry my friend i know i boring you a lot but you are so nice and helpfull and usually i dont ask help to fix anything because people most of the time are very rude.

Yasterday i tried bitbucket, download it etx without problem but i didnt find how to link it to eclipse without svn or git or something else

**Comment by Lucheti29** [comment]
For the new versions you must to use gradle, so depends on the IDE how to import the project.

Eclipse use a plugin todo integrate gradle. Read more here https://gradle.org/eclipse/

If you use Intellij, gradle support is integrated.

With eclipse or intellij, you have to download the core and datapack in the same folder. Then, import the datapack project as gradle project. The core project Will be imported because is a dependency of datapack.

**Comment by Nayden87** [comment]
Ok thank you so much. ill try to find a guid how to build the server with intellij. lets give a chance to this aswell and see how is working.
I just subscribed to your forum and i see you are looking for someone to make a logo..if you are still interested i can do it if you want,

**Comment by Lucheti29** [comment]
Sounds great! :D

**Comment by Nayden87** [comment]
if you wanna leave me your email or skype so ill send yu the logo when is ready.

**Comment by Lucheti29** [comment]
I don't use Skype, just telegram.

**Comment by Nayden87** [comment]
![error2](https://cloud.githubusercontent.com/assets/19366377/21583364/7486310a-d075-11e6-9692-e141baebb560.jpg)

Mate any idea how to solve this?

**Comment by Lucheti29** [comment]
Probably the event engine jar was not loaded because the class is unrecognizable.

**Comment by Nayden87** [comment]
im trying to install athenacore master even if its totaly different.
I checked the evengine.java in both version and the version 2.2 seems to be empy. 3 lines code and that it.

**Comment by Lucheti29** [comment]
It's diferent. In the last versions the logic is inside the jar. I suggest you wait for the new version where new features Will be introduces :)

I'm going to return from vacations in one week, then i'll start to work on engine again.

Probably you dont know but the Main idea of the engine is provide a Nice API to the developers to be more easy create new events without touching the l2jserver core. If you are interested about new changes, checkout the branch luksdlt92/jarloader

**Comment by Nayden87** [comment]
nothing..apparently the server is not loading at all the jar file. i can spawn npc and everything but if i read the console there is nothing about eventengine. So i dont know i was interested in CTF event that it.

**Comment by Lucheti29** [comment]
Checkout the last version. Keep in mind that you must use a last L2J version (that uses gradle at least), if not, the engine won't work.
