### ISSUE TITLE
Event messages

### ISSUE THREAD

**Issue by u3games** [AthenaEventEngine/AthenaCore#17]
[EN] - No alerts when the event ends (countdown show).
[ES] - No avisa cuando termina el evento (mostrar cuenta atras).

**Comment by fissban** [comment]
Interesante, seguro hoy armo algo para q vean  para mostrar

**Comment by u3games** [comment]
Claro, lo ideal seria añadirlo dentro del evento.
Ejemplo, texto en la parte inferior derecha de la pantalla.

**Comment by Lucheti29** [comment]
Con esto -> https://github.com/u3games/L2J_EventEngine/tree/feature/custom-scheduled-events es muy fácil agregar esto y se puede customizar por evento

**Comment by u3games** [comment]
https://github.com/u3games/L2J_EventEngine/pull/46

Pero lo ideal ahora es completarlo un poco, eso de que estas en el evento y de repente finalice no se ve bien. Lo ideal seria que indique... quedan X segundos para finalizar, ya sea en un margen de la pantalla o en el chat. Aun que estaria bien ambos ^^

Si es en el chat, se supone que al menos, indique..
- Quenda 10 segundos para finalizar el evento.
- Quedan 5 segundos..
- Evento finalizado.
- En unos segundos seras teletransportado.
