### ISSUE TITLE
Some help to implement this

### ISSUE THREAD

**Issue by iCodyRo** [AthenaEventEngine/AthenaCore#172]
I have make all Steps from Wiki but my NPC do not looks like on photos or how must to look.

![shot00000](https://cloud.githubusercontent.com/assets/7517325/24833291/046a5eb0-1ccd-11e7-9031-24dfcd2ba04a.jpg)
![shot00001](https://cloud.githubusercontent.com/assets/7517325/24833290/04682ce4-1ccd-11e7-8045-6799ca551f64.jpg)

What i must to do in this case?

**Comment by Lucheti29** [comment]
Hi there. I have a few questions:

a) Do you have any error in console? 
b) Did you see if the engine was loaded? 
c) Did you enable the custom npcs?
d) What version of L2J Server do you use?

**Comment by iCodyRo** [comment]
Hi @luksdlt92 ,

a) I don't see any error
b) I'm not sure where can i see this on server load
c) Yes
d) I'm not sure... The latest version of "master"

Maybe you have time to join with teamviewer...


Thank you.

**Comment by Lucheti29** [comment]
Sorry, I got home yesterday. I'm going to see your report today. :)

**Comment by iCodyRo** [comment]
Waiting @luksdlt92 :+1:

**Comment by u3games** [comment]
I test now and no errors.... pls use wiki guide.

**Comment by Lucheti29** [comment]
@iCodyRo I'm so sorry, I was very very busy :( I'll try to see it the next days.

**Comment by iCodyRo** [comment]
All right
