### ISSUE TITLE
Error to create new player

### ISSUE THREAD

**Issue by u3games** [AthenaEventEngine/AthenaCore#173]
![photo_2017-04-20_20-16-04](https://cloud.githubusercontent.com/assets/5102409/25249444/27f827ec-2612-11e7-9a0c-11fbbcf7ee4a.jpg)

**Comment by Lucheti29** [comment]
It should be fixed in the last release. Please test it, if the issue persists, re-open it.

https://github.com/AthenaEventEngine/AthenaCore/releases/tag/alpha-v3.3
