### ISSUE TITLE
Error on Start Server

### ISSUE THREAD

**Issue by iCodyRo** [AthenaEventEngine/AthenaCore#174]
I've make fresh install and i get this **error**
I've make every each step from the **Install Guide**
![error](https://cloud.githubusercontent.com/assets/7517325/25330380/1fc6f5c0-28e8-11e7-8bcb-703676199520.jpg)

**Comment by Lucheti29** [comment]
I don't know if you solve the issue but look at the wiki. In the steps 2 and 3:

> 2. Open EventEngine.rar, go to 'libs' folder and copy L2J_EventEngine.jar. Paste it inside dist/libs in L2J_Server project.
> 3. Inside L2J_Server project, run gradlew.bat to compile the project (also, you can do it with IDE, it's your choice). We need this to get a l2jserver.jar which recognizes the engine. Inside build/distributions will appear the last compilation and open it.

Basicly, that error is because the core don't recognize the engine. Did you add L2J_EventEngine.jar inside libs folder and recompile the L2J server? You must use that l2jserver.jar.

**Comment by iCodyRo** [comment]
Already solved ty. But i have another problem... Buttons appears like %Button% etc...

**Comment by Lucheti29** [comment]
@iCodyRo do you have the language folder inside dist/game/eventengine? Could you show me a screen of the game?

**Comment by iCodyRo** [comment]
I have this problem just on the Event **INFO**
This error has occurred since the installation.

![1](https://cloud.githubusercontent.com/assets/7517325/25565052/f4fea050-2dc8-11e7-8487-7763ba37df7c.jpg)
![2](https://cloud.githubusercontent.com/assets/7517325/25565053/f500ab84-2dc8-11e7-8d3d-7dfc18464133.jpg)

**Comment by Lucheti29** [comment]
@iCodyRo That should be fixed in the [LAST RELEASE](https://github.com/AthenaEventEngine/AthenaCore/releases/tag/alpha-v3.3). Please, checkout.

Keep in mind you must follow the setup guide again because the engine jar name changed (you have to recompile the l2jserver.jar with the new engine jar inside libs folder). Also, remove the old jar (L2J_EventEngine.jar).

**Comment by iCodyRo** [comment]
Solved. Thank you.
