### ISSUE TITLE
NPE to kill door

### ISSUE THREAD

**Issue by u3games** [AthenaEventEngine/AthenaCore#175]
![imagen](https://cloud.githubusercontent.com/assets/5102409/25578563/3cc67d8e-2e70-11e7-8a19-db7775f3da51.png)

**Comment by Lucheti29** [comment]
It should be fixed in the last release. Please test it, if the issue persists, re-open it.

https://github.com/AthenaEventEngine/AthenaCore/releases/tag/alpha-v3.3
