### ISSUE TITLE
registering_dualbox_limit

### ISSUE THREAD

**Issue by iCodyRo** [AthenaEventEngine/AthenaCore#178]
I make some changes on server settings but i dont remember which and now i get this message when i try to Register on event. The vote event work.

I don't have DualBox when i get this message.

![dfh](https://cloud.githubusercontent.com/assets/7517325/25723490/dba07236-3120-11e7-99a4-ad120c733d26.jpg)

**Comment by Lucheti29** [comment]
Check your language xml, probably it's not the last one

**Comment by iCodyRo** [comment]
Yes, now i get the message but not is this the big problem what i mean. The real problem is the register on event. I Cant Register on it...

**Comment by Lucheti29** [comment]
Yeap

**Comment by iCodyRo** [comment]
I get this message **Sorry, you exceeded the dualbox limit.** when i push on the Register. And i dont have another client/char opened/on. I don't have an dualbox.

**Comment by Lucheti29** [comment]
That's right. What's the problem? Did you enable the dualbox protection and set the limit to 1?

**Comment by iCodyRo** [comment]
Maybe i make an mistake with this... im not sure. Where can i check this setting?

**Comment by Lucheti29** [comment]
Check at the bottom of https://github.com/AthenaEventEngine/AthenaCore/blob/master/dist/game/eventengine/EventEngine.conf

**Comment by iCodyRo** [comment]
So it's False

# Dualbox settings
dualbox.enabled = False
dualbox.maxAllowed = 1


Yesterday i have set the server Custom Components all True from the General.Properties nothing else.

**Comment by Lucheti29** [comment]
That's weird. Let me check when I get home.

**Comment by iCodyRo** [comment]
Ok please. It's strange for me too

**Comment by Lucheti29** [comment]
I found the bug. I will give you a message when the fix is uploaded.

**Comment by iCodyRo** [comment]
Ok @luksdlt92 ty

**Comment by Lucheti29** [comment]
@iCodyRo Could you check the last release again pls? https://github.com/AthenaEventEngine/AthenaCore/releases/tag/alpha-v3.3.1

You just have to replace the AthenaCore.jar inside libs folder. It's not necessary recompile the l2jserver.
