### ISSUE TITLE
Karma Player in event.

### ISSUE THREAD

**Issue by u3games** [AthenaEventEngine/AthenaCore#18]
Cuando matas a un jugador sin que este te haya atacado, te vuelves PK. Se deberia de implementar en el engine que una vez que te teletransporte a la instancia, esta la detecte como zona PvP, para evitar este tipo de bugs. Que a la hora de utilizar skills son muy molestos por tener que pulsar control.

**Comment by Lucheti29** [comment]
Fixed https://github.com/u3games/L2J_EventEngine/pull/24
