### ISSUE TITLE
The original color of the title is not restored when the event finishes

### ISSUE THREAD

**Issue by Lucheti29** [AthenaEventEngine/AthenaCore#191]

**Comment by Lucheti29** [comment]
Also the title is not restored

**Comment by josellyto** [comment]
It would be interesting to change the title for the equal aura of the champions in the feet

**Comment by Lucheti29** [comment]
@josellyto What do you mean?

**Comment by josellyto** [comment]
instead of modifying the subnick, add this:
https://i.imgur.com/WRaGsMS.jpg

**Comment by Lucheti29** [comment]
It wouldn't be possible because the Team vs Team can be with multiple teams and you have just two effects.  Another idea could be enable different effects for the different teams by config.
