### ISSUE TITLE
Some errors on last rev

### ISSUE THREAD

**Issue by CostyKiller** [AthenaEventEngine/AthenaCore#198]
![errors](https://user-images.githubusercontent.com/8811111/36420377-80709f3c-163d-11e8-8cb8-0f9a15ea735e.jpg)

**Comment by Lucheti29** [comment]
Seems like your Gradle configuration is not working because the entire list of errors is about dependencies. Did you setup the project as Gradle project?

**Comment by u3games** [comment]
![imagen](https://user-images.githubusercontent.com/5102409/36422758-c17b7c36-163d-11e8-8873-7bc1830a58cc.png)

Check pls ^^

**Comment by CostyKiller** [comment]
yes is working now, thanks for quick reply.
