### ISSUE TITLE
Deslogueo + Localización

### ISSUE THREAD

**Issue by Lucheti29** [AthenaEventEngine/AthenaCore#21]
Al desloguearse un jugador del evento, debería loguear en la localización donde se registró.

**Comment by u3games** [comment]
No bastaria con editar el "Logout.java" y añadir la condición del si el jugador desloguea y esta participando en el evento te teletransporte a las coordenadas del npc ¿?

**Comment by Lucheti29** [comment]
O puede guardar un returnLocation cuando participa en un evento, y al finalizar o desloguear, mandarlo ahí.

**Comment by u3games** [comment]
Fix https://github.com/u3games/L2J_EventEngine/commit/58a9b1197ed27b3df5fa8cf9d55ee44f121c6f0d
