### ISSUE TITLE
NullPointerException - L2Character.doDie

### ISSUE THREAD

**Issue by u3games** [AthenaEventEngine/AthenaCore#23]
![bug](https://cloud.githubusercontent.com/assets/5102409/8497820/90df6bd2-2180-11e5-9a83-31778786deb7.png)

**Comment by u3games** [comment]
Fix in Rev 43 --> https://github.com/u3games/L2J_EventEngine/commit/59b9abacd76fd4b6a92ca8fda14326e03f8064a1

**Comment by Lucheti29** [comment]
It was fixed here https://github.com/u3games/L2J_EventEngine/pull/24
