### ISSUE TITLE
NPE on revive

### ISSUE THREAD

**Issue by Lucheti29** [AthenaEventEngine/AthenaCore#26]
Si el jugador muere, está esperando a que lo reviva el evento y en ese intervalo el evento termina, arroja un NPE.

**Comment by u3games** [comment]
Yo no he visto NPE en consola, pero si es cierto.
- Si un jugador muere justo cuando finaliza el evento (all vs all por ejemplo), lo deja muerto y no lo teletransporta.

**Comment by u3games** [comment]
Already Fix --> https://github.com/u3games/L2J_EventEngine/commit/f5e0c88477a37922d84c583d70215a766617189a
