### ISSUE TITLE
manejo de los estados del evento engine

### ISSUE THREAD

**Issue by fissban** [AthenaEventEngine/AthenaCore#29]
la variable "_state" arranca con "WAITING" y el tiempo se inicia con el default para arrancar un evento por lo q si seteo para q se ejecuten los eventos cada una hora seria 1hs esperando q cambie el estado de WAITING a REGISTER y tengo q esperar otra hora mas y el estado de "REGISTER" jamas se  ejecuta ya q esta condicionado mal

**Comment by Lucheti29** [comment]
No estoy de acuerdo con eso.

EventInterval es el tiempo del WAITING.

EventRegisterTime es el tiempo de registro

En otras palabras, no necesariamente es una hora de una cosa y una hora de la otra porque se manejan separado.

Por otra parte, ¿por qué decís que está mal condicionado?
