### ISSUE TITLE
Score al finalizar evento

### ISSUE THREAD

**Issue by Lucheti29** [AthenaEventEngine/AthenaCore#3]
Queda el score al finalizar el evento (rama unstable)

![bug1](https://cloud.githubusercontent.com/assets/4108820/8401024/dc470272-1dfe-11e5-9ce2-e7ed46190907.png)

**Comment by fissban** [comment]
Ya fue quitado el uso de este paquete cliente<->server hasta que aprenda a usarlo correctamente
