### ISSUE TITLE
Tag incorrect

### ISSUE THREAD

**Issue by u3games** [AthenaEventEngine/AthenaCore#41]
Al loguear, aparece el siguiente mensaje:

![bug_tag_message](https://cloud.githubusercontent.com/assets/5102409/8984374/7a17ebde-36d1-11e5-8ae1-f43374147bb8.png)

Aparece ":" antes del mensaje.

**Comment by u3games** [comment]
Fix:

Index: EventEngineManager.java
===================================================================
--- EventEngineManager.java	(revision 103)
+++ EventEngineManager.java	(working copy)
@@ -359,8 +359,8 @@
 	 */
 	public static void listenerOnLogin(L2PcInstance player)
 	{
-		player.sendPacket(new CreatureSay(0, Say2.PARTYROOM_COMMANDER, "", MessageData.getMsgByLang(player, "event_login_participate", true)));
-		player.sendPacket(new CreatureSay(0, Say2.PARTYROOM_COMMANDER, "", MessageData.getMsgByLang(player, "event_login_vote", true)));
+		player.sendPacket(new CreatureSay(0, Say2, "", MessageData.getMsgByLang(player, "event_login_participate", true)));
+		player.sendPacket(new CreatureSay(0, Say2, "", MessageData.getMsgByLang(player, "event_login_vote", true)));
 	}
 	
 	/**

**Comment by u3games** [comment]
A la hora de morir un personaje, pasa lo mismo:

![bug_dead_message](https://cloud.githubusercontent.com/assets/5102409/8984330/2755585a-36d1-11e5-81b8-c0e51b590887.png)

**Comment by u3games** [comment]
A la hora de morir, pasa lo mismo:

![bug_end_event_message](https://cloud.githubusercontent.com/assets/5102409/8984344/3ba4bfe4-36d1-11e5-8943-c4e8105571a8.png)

**Comment by fissban** [comment]
Esto es algo que no se podrá ajustar como tu quieres ya que a excepción de "announcement" y "critical_announcement" los demás  paquetes esta echos para que salga primero el nombre de un personaje y nosotros no ponemos ninguno ya que usamos el tag "[EventEngine]"  por lo que cierro este tema.
