### ISSUE TITLE
Kills Title Player

### ISSUE THREAD

**Issue by u3games** [AthenaEventEngine/AthenaCore#42]
- Rev: Last Vers
- Event: All vs All

[EN] After the event, the title remains.
[ES] Al finalizar el evento, el titulo permanece.

[ES] Cuando matas a un personaje, no te suma la cantidad de muertes realizadas. Pero si, se suma cuando mueres.

[EN] When you kill a character, do not add the number of deaths made. But, it adds when you die.

![bug_title_event](https://cloud.githubusercontent.com/assets/5102409/8858825/065a01a2-317a-11e5-9786-a958625dd3d2.png)

**Comment by Lucheti29** [comment]
Ya tenemos conocimiento de esto. Está mal el parche del listener.

**Comment by fissban** [comment]
Esto ya fue reparado
