### ISSUE TITLE
Rewards for all!!

### ISSUE THREAD

**Issue by u3games** [AthenaEventEngine/AthenaCore#43]
[ES] Todos los jugadores, reciben recompensa. Aún que pierdas.
[EN] All players receive a reward. Even you lose.

All events.

**Comment by Lucheti29** [comment]
Seguramente sea porque no se suman puntos cuando matás jugadores de otro equipo, por ejemplo, en TvT (ya estamos en vías de fixearlo).

**Comment by fissban** [comment]
ya fue reparado
