### ISSUE TITLE
One Vs One - Bugs

### ISSUE THREAD

**Issue by u3games** [AthenaEventEngine/AthenaCore#52]
## Evento One Vs One

El contador de muertes esta mal, cuando matas a un jugador te añade +1 pero al que has matado le da -1, adjunto imagen:

![bug_ovo_kills](https://cloud.githubusercontent.com/assets/5102409/9008318/ad0374be-3799-11e5-85b3-0cb11ecf0356.png)

Cuando finaliza el evento, no teletransporta a los jugadores

Muestra errores en consola del gameserver, adjunto imagen:

![bug_gs](https://cloud.githubusercontent.com/assets/5102409/9008832/40a1b368-379d-11e5-8356-d11046d28eef.png)

No da recompensa al ganador.

IMPORTANTE: El titulo si cambia aqui, cuando fianliza el evento.

**Comment by fissban** [comment]
tienes q tener en cuenta q un error en el codigo puede ocacionar q se generen  varios errores luego como el no dar la recomenza o algo asi....asiq lo q suceda luego del error ya no es confiable.

**Comment by u3games** [comment]
El evento no finaliza por este error...

**Comment by fissban** [comment]
Esto ya fue reparado
