### ISSUE TITLE
Suicide Player

### ISSUE THREAD

**Issue by u3games** [AthenaEventEngine/AthenaCore#62]
Cuando el jugador se suicida, por ejemplo.. utilizas el comando kill para ti mismo, adquieres recompensas y muertes, por lo que puedes ganar incluso el evento matandote.

Creo que ya es hora de añadirle protección anti-DualBox y que se detecte si es el mismo player en las muertes.

**Comment by Lucheti29** [comment]
Lo del dualbox va en otro issue. Respecto a lo primero, good catch.

**Comment by fissban** [comment]
como podrias matarte a ti mismo siendo un player normal?

sobre el dualBox yo tengo un sistema que por medio del trace verifica si las cuentas estan en la misma pc o no...mas util q el simple dualbox de l2jserver

**Comment by u3games** [comment]
Con respecto a las ip,s yo utilizo lo siguente. Mirar a ver que os parece ^^

// kpvpwi = killerPlayerInstance PvP War Instance
// kpvpwi = targetPlayerInstance PvP War Instance

final L2PcInstance kpvpwi = event.getAttacker().getActingPlayer();
final L2PcInstance tpvpwi = event.getTarget().getActingPlayer();
final String ip1 = kpvpwi.getClient().getConnection().getInetAddress().getHostAddress();
final String ip2 = tpvpwi.getClient().getConnection().getInetAddress().getHostAddress();

**Comment by fissban** [comment]
cierro esto, no existe forma de que un player normal se suicide solo y el dual box ya se esta tratando en un branch.
