### ISSUE TITLE
Player Instance

### ISSUE THREAD

**Issue by u3games** [AthenaEventEngine/AthenaCore#63]
En algunos casos, cuando son teletransportados a las arenas, no se teletransportan en la misma instancia. Por lo que no pueden luchar..

**Comment by fissban** [comment]
wow....intentare mejorar la parte del codigo q respecta a eso

**Comment by Lucheti29** [comment]
Es muy factible que sea problema de L2J.

**Comment by u3games** [comment]
Add missing labels

**Comment by u3games** [comment]
Old Bug, already fixed.
