### ISSUE TITLE
Result --> Tie

### ISSUE THREAD

**Issue by u3games** [AthenaEventEngine/AthenaCore#71]
Missing Tie properties and code...

![2](https://cloud.githubusercontent.com/assets/5102409/12822867/41525478-cb6a-11e5-8c53-1c2b6e1d13c3.png)

Rewards for all equip :-1:

**Comment by fissban** [comment]
Este tipo de cosas estan condicionadas directamente dentro de cada evento, aunque si se cree necesario podemos estipular algo especifico para todos los eventos o su mayoria,

**Comment by ghost** [comment]
Continues to happen?

**Comment by Lucheti29** [comment]
Continues

**Comment by Lucheti29** [comment]
If you use RewardHelper (https://github.com/AthenaEventEngine/AthenaCore/blob/develop/src/main/java/com/github/athenaengine/core/helper/RewardHelper.java) it's too easy to handle the Tie result. Also, all the base events are handling it right now.
