### ISSUE TITLE
Enabled Event Engine Setting

### ISSUE THREAD

**Issue by u3games** [AthenaEventEngine/AthenaCore#74]
Add setting for enabled/disabled event engine in properties ;)

**Comment by Lucheti29** [comment]
Desde este commit https://github.com/u3games/L2J_EventEngine/commit/43108cdce2d4ed01dfc2e4c6c7cea622f9069167 lo veo absolutamente innecesario. Si no querés el engine, tan sólo borrá el script que lo inicializa (como cualquier evento de L2J).

Si estás de acuerdo, me parece conveniente cerrar este issue.

**Comment by u3games** [comment]
Cierto, cierro pues ^^
