### ISSUE TITLE
Condiciones para votar

### ISSUE THREAD

**Issue by Lucheti29** [AthenaEventEngine/AthenaCore#82]
Deberían respetarse las mismas condiciones para registrarse a un evento que para votar. Sino, jugadores lvl 1 (por ejemplo) pueden votar por más que no puedan participar.

**Comment by u3games** [comment]
Cierto.

**Comment by fissban** [comment]
Aqui ya lo hice
https://github.com/u3games/L2J_EventEngine/pull/96
