### ISSUE TITLE
Reward en Team vs Team

### ISSUE THREAD

**Issue by Lucheti29** [AthenaEventEngine/AthenaCore#89]
# Test Event: Team vs Team
- Reconoce las muertes

![event_tvt_test_1](https://cloud.githubusercontent.com/assets/5102409/10667458/cabf3a54-78d7-11e5-8895-c4d78dd633be.png)

 pero a la hora de dar recompensas al equipo ganador, no ocurre nada. No entrega recompensa:

![event_tvt_test_2](https://cloud.githubusercontent.com/assets/5102409/10667202/5c29bc00-78d6-11e5-9d75-f162654f3dbc.png)

Reportado por @u3games

**Comment by u3games** [comment]
Lo mismo pasa con el evento CTF, al parecer es cuando el ganador son los miembros de un equipo.

**Comment by u3games** [comment]
Fix in https://github.com/u3games/L2J_EventEngine/commit/02104a48545a283fb72807dd5654e363a6c654be, close ^^
