### ISSUE TITLE
Sin mínimo de participantes

### ISSUE THREAD

**Issue by Lucheti29** [AthenaEventEngine/AthenaCore#9]
No pide el mínimo de participantes para empezar el evento, solamente si la lista no es vacía.

**Comment by u3games** [comment]
Y tampoco si esta vacia.. ejemplo:

Pulsas sobre un evento (automaticamente aumenta voto y te registras en el) y luego desconectas. El voto sigue ahi y el registro tambien. Pero cuando inicia el evento, a pesar de que no haya nadie registrado se inicia (por el falso almacenamiento de registros y votos).

**Comment by Lucheti29** [comment]
No es un falso almacenamiento sino que nunca considera que el jugador deslogueó.

**Comment by Lucheti29** [comment]
Fixeado en este PR -> https://github.com/u3games/L2J_EventEngine/pull/22
