### ISSUE TITLE
CTF Event - Test Bug List

### ISSUE THREAD

**Issue by u3games** [AthenaEventEngine/AthenaCore#90]
- En todas las banderas y holders, aparece el titulo/name de "Equipo Azul". Muestro imagen del spawn del equipo rojo:

![test_ctf_bug](https://cloud.githubusercontent.com/assets/5102409/10698937/bda15b72-79b3-11e5-8153-d895e59fd076.png)
- No se, pero creo que esto se reparó.... al capturar/plantar bandera, sale esta molesta ventana:

![test_ctf_bug_2](https://cloud.githubusercontent.com/assets/5102409/10698955/d085601c-79b3-11e5-9023-42849e940046.png)
- Cuando obtienes la bandera de un equipo rival e ir a tu base a colocarla, la colocas desde lejos. Visualmente queda fatal, ya que aun no ha llegado al holder de tu equipo y ya has colocado bandera.

**Comment by fissban** [comment]
@u3games aqui repare todo :d
https://github.com/u3games/L2J_EventEngine/pull/93
Aprobalo y hacemos el merge.
